# Docker image for spyro's base environment

FROM docker.io/ubuntu:20.04

MAINTAINER Joao Moreira <bapdmdias@usp.com>

USER root

##########   USAGE INSTRUCTIONS   ##########
# Build the image
# > docker build --file Dockerfile.env --tag spyro-env:latest .

##########   BASE CONFIGURATION   ##########
# Most commands in this section are copy pasted from Firedrake's base 
# Dockerfile at https://hub.docker.com/r/firedrakeproject/firedrake/dockerfile.
# We don't build FROM it so that the install command can be customized.

# Install necessary packages
RUN apt-get update \
    && apt-get -y dist-upgrade \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata \
    && apt-get -y install curl vim \
                 openssh-client build-essential autoconf automake \
                 cmake gfortran git libblas-dev liblapack-dev \
                 libmpich-dev libtool mercurial mpich\
                 python3-dev python3-pip python3-tk python3-venv \
                 zlib1g-dev libboost-dev sudo \
                 # needed for scotch
                 bison flex \ 
                 # needed for seismicmesh
		 libcgal-dev \
                 # needed for cplex
                 default-jre \
    && rm -rf /var/lib/apt/lists/*

# Use supposedly sane locale
ENV LC_ALL C.UTF-8

# Set up user so that we do not run as root
RUN useradd -m -s /bin/bash -G sudo firedrake && \
    echo "firedrake:docker" | chpasswd && \
    echo "firedrake ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    ldconfig

